import { FastifyInstance } from 'fastify';
import { z } from 'zod';
import axios from 'axios';
import ytdl from '@distube/ytdl-core';
import ytdlExec from 'yt-dlp-exec';
import fs from 'fs';
import path from 'path';
import { prisma } from '../prisma/client';
import { authenticate } from '../middleware/auth.middleware';
import { config } from '../config';

// Load YouTube agent cookies from project root if it exists
let ytdlAgent: any = undefined;
try {
  const cookiesPath = path.join(process.cwd(), 'youtube_cookies.json');
  if (fs.existsSync(cookiesPath)) {
    const cookies = JSON.parse(fs.readFileSync(cookiesPath, 'utf8'));
    ytdlAgent = ytdl.createAgent(cookies);
    console.log('[MusicRouter] Loaded YouTube cookies agent successfully from youtube_cookies.json.');
  }
} catch (err) {
  console.warn('[MusicRouter] Failed to load youtube_cookies.json for ytdl agent:', err);
}

function convertJsonToNetscape(jsonCookies: any[]): string {
  let output = '# Netscape HTTP Cookie File\n# This file is generated by USCHAT\n\n';
  for (const cookie of jsonCookies) {
    const domain = cookie.domain || '.youtube.com';
    const flag1 = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const pathVal = cookie.path || '/';
    const flag2 = cookie.secure ? 'TRUE' : 'FALSE';
    const expiration = Math.floor(cookie.expirationDate || (Date.now() / 1000 + 3600 * 24 * 365));
    const name = cookie.name;
    const value = cookie.value;
    output += `${domain}\t${flag1}\t${pathVal}\t${flag2}\t${expiration}\t${name}\t${value}\n`;
  }
  return output;
}

const searchSchema = z.object({
  q: z.string().min(1),
});

const spotifyImportSchema = z.object({
  playlistUrl: z.string().url(),
});

const playlistCreateSchema = z.object({
  name: z.string().min(1).max(100),
});

const addTrackSchema = z.object({
  title: z.string().min(1),
  artist: z.string().min(1),
  album: z.string().optional().nullable(),
  duration: z.number().int().optional().nullable(),
  coverUrl: z.string().optional().nullable(),
  trackUri: z.string().url(),
});

async function searchYouTube(query: string): Promise<any[]> {
  try {
    const url = `https://www.youtube.com/results?search_query=${encodeURIComponent(query)}`;
    const response = await axios.get(url, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Accept-Language': 'en-US,en;q=0.9',
      },
      timeout: 5000,
    });

    const html = response.data;
    const regex = /var ytInitialData\s*=\s*({.+?});/;
    const match = regex.exec(html);
    if (!match) return [];

    const json = JSON.parse(match[1]);
    const contents = json.contents?.twoColumnSearchResultsRenderer?.primaryContents?.sectionListRenderer?.contents?.[0]?.itemSectionRenderer?.contents || [];

    const tracks: any[] = [];
    for (const item of contents) {
      const video = item.videoRenderer;
      if (!video) continue;

      const title = video.title?.runs?.[0]?.text || '';
      const videoId = video.videoId;
      if (!videoId) continue;

      const artist = video.ownerText?.runs?.[0]?.text || 'Unknown Artist';
      const durationText = video.lengthText?.simpleText || '3:00';
      
      const parts = durationText.split(':').map(Number);
      let duration = 0;
      if (parts.length === 2) {
        duration = parts[0] * 60 + parts[1];
      } else if (parts.length === 3) {
        duration = parts[0] * 3600 + parts[1] * 60 + parts[2];
      }

      const coverUrl = video.thumbnail?.thumbnails?.[0]?.url || null;
      const trackUri = `https://www.youtube.com/watch?v=${videoId}`;

      tracks.push({
        title,
        artist,
        duration,
        trackUri,
        coverUrl,
      });
    }
    return tracks;
  } catch (err) {
    console.error('[YouTubeSearch] Scraper failed:', err);
    return [];
  }
}

export async function musicRoutes(fastify: FastifyInstance) {
  // 1. Search Music via Lavalink Node (with direct YouTube scraper fallback)
  fastify.get('/search', { preHandler: [authenticate] }, async (request, reply) => {
    const { q } = searchSchema.parse(request.query);
    try {
      const lavalinkUrl = `http://${config.lavalink.host}:${config.lavalink.port}/v4/loadtracks`;
      const response = await axios.get(lavalinkUrl, {
        params: { identifier: `ytsearch:${q}` },
        headers: { Authorization: config.lavalink.password },
        timeout: 5000,
      });

      const data = response.data;
      const loadTypeUpper = String(data.loadType).toUpperCase();
      
      if ((loadTypeUpper === 'SEARCH' || loadTypeUpper === 'TRACK_LOADED') && Array.isArray(data.data) && data.data.length > 0) {
        const tracks = data.data.map((item: any) => ({
          title: item.info.title,
          artist: item.info.author,
          duration: Math.floor(item.info.length / 1000),
          trackUri: item.info.uri,
          coverUrl: item.info.artworkUrl || null,
        }));
        return reply.send(tracks);
      }
      
      // Fallback if Lavalink returned empty, search result load type was not matched, or errored
      fastify.log.warn('[MusicRouter] Lavalink search empty/unsupported. Attempting YouTube search fallback...');
      const fallbackTracks = await searchYouTube(q);
      return reply.send(fallbackTracks);
    } catch (err: any) {
      fastify.log.error(err, '[MusicRouter] Lavalink search request failed. Triggering YouTube search fallback...');
      const fallbackTracks = await searchYouTube(q);
      return reply.send(fallbackTracks);
    }
  });

  // 2. Direct Audio Stream Pipe (No HTTP redirect)
  fastify.get('/stream', { preHandler: [authenticate] }, async (request, reply) => {
    const { uri } = z.object({ uri: z.string().url() }).parse(request.query);
    try {
      fastify.log.info({ uri }, '[MusicRouter] Resolving stream with yt-dlp-exec...');

      const jsonCookiesPath = path.join(process.cwd(), 'youtube_cookies.json');
      const netscapeCookiesPath = path.join(process.cwd(), 'youtube_cookies.txt');

      // Convert JSON cookies to Netscape format on-the-fly for yt-dlp
      if (fs.existsSync(jsonCookiesPath)) {
        try {
          const jsonCookies = JSON.parse(fs.readFileSync(jsonCookiesPath, 'utf8'));
          const netscapeStr = convertJsonToNetscape(jsonCookies);
          fs.writeFileSync(netscapeCookiesPath, netscapeStr, 'utf8');
        } catch (err) {
          fastify.log.warn(err, '[MusicRouter] Failed to convert JSON cookies to Netscape format');
        }
      }

      const ytDlpOptions: any = {
        getUrl: true,
        format: 'bestaudio',
        jsRuntimes: 'node:' + process.execPath,
      };

      if (fs.existsSync(netscapeCookiesPath)) {
        ytDlpOptions.cookies = netscapeCookiesPath;
      }

      const streamUrl = (await ytdlExec(uri, ytDlpOptions)) as any;
      if (!streamUrl) {
        throw new Error('yt-dlp-exec returned empty stream URL');
      }

      fastify.log.info('[MusicRouter] Streaming format URL via Axios...');
      const response = await axios.get(streamUrl.trim(), {
        responseType: 'stream',
        headers: {
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
        }
      });

      reply.header('Content-Type', 'audio/mpeg');
      return reply.send(response.data);
    } catch (err: any) {
      fastify.log.error(err, '[MusicRouter] Stream resolution failed');
      return reply.status(500).send({ error: 'Resolution Failed', message: 'Failed to resolve audio stream link' });
    }
  });

  // 3. Spotify Metadata Import (Playlists, Albums, Tracks, Artists)
  fastify.post('/spotify-import', { preHandler: [authenticate] }, async (request, reply) => {
    const { playlistUrl } = spotifyImportSchema.parse(request.body);
    const userId = request.user.id;

    if (!config.spotify.clientId || !config.spotify.clientSecret) {
      return reply.status(400).send({
        error: 'Bad Request',
        message: 'Spotify Client Credentials are not configured on the server.',
      });
    }

    try {
      // Parse import type and ID from URL
      const playlistMatch = /\/playlist\/([a-zA-Z0-9]+)/.exec(playlistUrl);
      const albumMatch = /\/album\/([a-zA-Z0-9]+)/.exec(playlistUrl);
      const trackMatch = /\/track\/([a-zA-Z0-9]+)/.exec(playlistUrl);
      const artistMatch = /\/artist\/([a-zA-Z0-9]+)/.exec(playlistUrl);

      let importType: 'playlist' | 'album' | 'track' | 'artist' | null = null;
      let spotifyId = '';

      if (playlistMatch) {
        importType = 'playlist';
        spotifyId = playlistMatch[1];
      } else if (albumMatch) {
        importType = 'album';
        spotifyId = albumMatch[1];
      } else if (trackMatch) {
        importType = 'track';
        spotifyId = trackMatch[1];
      } else if (artistMatch) {
        importType = 'artist';
        spotifyId = artistMatch[1];
      }

      if (!importType) {
        return reply.status(400).send({ error: 'Bad Request', message: 'Invalid Spotify URL. Must be a playlist, album, track, or artist URL.' });
      }

      // 1. Get Spotify Client Access Token
      const tokenRes = await axios.post(
        'https://accounts.spotify.com/api/token',
        'grant_type=client_credentials',
        {
          headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            Authorization: `Basic ${Buffer.from(
              `${config.spotify.clientId}:${config.spotify.clientSecret}`
            ).toString('base64')}`,
          },
        }
      );
      const accessToken = tokenRes.data.access_token;

      let tracksList: any[] = [];
      let playlistName = 'Imported Spotify List';
      let coverUrl = null;

      // 2. Fetch appropriate type metadata from Spotify APIs
      if (importType === 'playlist') {
        const res = await axios.get(`https://api.spotify.com/v1/playlists/${spotifyId}`, {
          headers: { Authorization: `Bearer ${accessToken}` },
        });
        playlistName = res.data.name || 'Imported Playlist';
        coverUrl = res.data.images?.[0]?.url || null;
        tracksList = (res.data.tracks?.items || [])
          .filter((item: any) => item.track)
          .map((item: any) => item.track);
      } else if (importType === 'album') {
        const res = await axios.get(`https://api.spotify.com/v1/albums/${spotifyId}`, {
          headers: { Authorization: `Bearer ${accessToken}` },
        });
        playlistName = res.data.name || 'Imported Album';
        coverUrl = res.data.images?.[0]?.url || null;
        tracksList = (res.data.tracks?.items || []).map((t: any) => ({
          ...t,
          album: { images: res.data.images, name: res.data.name },
        }));
      } else if (importType === 'track') {
        const res = await axios.get(`https://api.spotify.com/v1/tracks/${spotifyId}`, {
          headers: { Authorization: `Bearer ${accessToken}` },
        });
        playlistName = res.data.name || 'Imported Track';
        coverUrl = res.data.album?.images?.[0]?.url || null;
        tracksList = [res.data];
      } else if (importType === 'artist') {
        const res = await axios.get(`https://api.spotify.com/v1/artists/${spotifyId}/top-tracks?market=US`, {
          headers: { Authorization: `Bearer ${accessToken}` },
        });
        const artistMeta = await axios.get(`https://api.spotify.com/v1/artists/${spotifyId}`, {
          headers: { Authorization: `Bearer ${accessToken}` },
        });
        playlistName = `${artistMeta.data.name || 'Artist'} Top Tracks`;
        coverUrl = artistMeta.data.images?.[0]?.url || null;
        tracksList = res.data.tracks || [];
      }

      // 3. Create Playlist Record in DB
      const dbPlaylist = await prisma.playlist.create({
        data: {
          userId,
          name: playlistName,
          coverUrl,
        },
      });

      // 4. Save tracks list to DB
      const tracksToCreate = [];
      for (let i = 0; i < tracksList.length; i++) {
        const track = tracksList[i];
        if (!track) continue;

        const trackName = track.name;
        const artistName = track.artists?.map((a: any) => a.name).join(', ') || 'Unknown';
        const albumName = track.album?.name || null;
        const durationSecs = Math.floor((track.duration_ms || 0) / 1000);
        const trackCover = track.album?.images?.[0]?.url || coverUrl;

        const searchQuery = `${trackName} ${artistName}`;
        const searchUri = `https://www.youtube.com/results?search_query=${encodeURIComponent(searchQuery)}`;

        tracksToCreate.push({
          playlistId: dbPlaylist.id,
          title: trackName,
          artist: artistName,
          album: albumName,
          duration: durationSecs,
          coverUrl: trackCover,
          trackUri: searchUri,
          position: i,
        });
      }

      if (tracksToCreate.length > 0) {
        await prisma.playlistTrack.createMany({
          data: tracksToCreate,
        });
      }

      // Fetch the created playlist with its tracks
      const populated = await prisma.playlist.findUnique({
        where: { id: dbPlaylist.id },
        include: { tracks: { orderBy: { position: 'asc' } } },
      });

      return reply.status(201).send(populated);
    } catch (err: any) {
      fastify.log.error(err, '[MusicRouter] Spotify import error');
      return reply.status(500).send({
        error: 'Import Failed',
        message: err.response?.data?.error?.message || 'Failed to import Spotify item',
      });
    }
  });

  // 4. Playlists CRUD Endpoints
  fastify.get('/playlists', { preHandler: [authenticate] }, async (request, reply) => {
    const playlists = await prisma.playlist.findMany({
      where: { userId: request.user.id },
      include: {
        _count: { select: { tracks: true } },
      },
      orderBy: { createdAt: 'desc' },
    });
    return reply.send(playlists);
  });

  fastify.post('/playlists', { preHandler: [authenticate] }, async (request, reply) => {
    const { name } = playlistCreateSchema.parse(request.body);
    const playlist = await prisma.playlist.create({
      data: {
        userId: request.user.id,
        name,
      },
    });
    return reply.status(201).send(playlist);
  });

  fastify.get('/playlists/:id', { preHandler: [authenticate] }, async (request, reply) => {
    const { id } = request.params as { id: string };
    const playlist = await prisma.playlist.findFirst({
      where: { id, userId: request.user.id },
      include: {
        tracks: { orderBy: { position: 'asc' } },
      },
    });

    if (!playlist) {
      return reply.status(404).send({ error: 'Not Found', message: 'Playlist not found' });
    }
    return reply.send(playlist);
  });

  fastify.delete('/playlists/:id', { preHandler: [authenticate] }, async (request, reply) => {
    const { id } = request.params as { id: string };
    await prisma.playlist.deleteMany({
      where: { id, userId: request.user.id },
    });
    return reply.send({ success: true });
  });

  fastify.post('/playlists/:id/tracks', { preHandler: [authenticate] }, async (request, reply) => {
    const { id } = request.params as { id: string };
    const body = addTrackSchema.parse(request.body);

    const playlist = await prisma.playlist.findFirst({
      where: { id, userId: request.user.id },
    });

    if (!playlist) {
      return reply.status(404).send({ error: 'Not Found', message: 'Playlist not found' });
    }

    const count = await prisma.playlistTrack.count({ where: { playlistId: id } });

    const newTrack = await prisma.playlistTrack.create({
      data: {
        playlistId: id,
        title: body.title,
        artist: body.artist,
        album: body.album,
        duration: body.duration,
        coverUrl: body.coverUrl,
        trackUri: body.trackUri,
        position: count,
      },
    });

    return reply.status(201).send(newTrack);
  });

  fastify.delete('/playlists/:id/tracks/:trackId', { preHandler: [authenticate] }, async (request, reply) => {
    const { id, trackId } = request.params as { id: string; trackId: string };
    
    const playlist = await prisma.playlist.findFirst({
      where: { id, userId: request.user.id },
    });

    if (!playlist) {
      return reply.status(404).send({ error: 'Not Found', message: 'Playlist not found' });
    }

    await prisma.playlistTrack.delete({
      where: { id: trackId },
    });

    return reply.send({ success: true });
  });

  // 5. Liked Songs Endpoints
  fastify.get('/liked-songs', { preHandler: [authenticate] }, async (request, reply) => {
    const liked = await prisma.likedSong.findMany({
      where: { userId: request.user.id },
      orderBy: { createdAt: 'desc' },
    });
    return reply.send(liked);
  });

  fastify.post('/liked-songs', { preHandler: [authenticate] }, async (request, reply) => {
    const body = addTrackSchema.parse(request.body);
    const userId = request.user.id;

    const liked = await prisma.likedSong.create({
      data: {
        userId,
        title: body.title,
        artist: body.artist,
        album: body.album,
        duration: body.duration,
        coverUrl: body.coverUrl,
        trackUri: body.trackUri,
      },
    });

    return reply.status(201).send(liked);
  });

  fastify.delete('/liked-songs/:id', { preHandler: [authenticate] }, async (request, reply) => {
    const { id } = request.params as { id: string };
    await prisma.likedSong.deleteMany({
      where: { id, userId: request.user.id },
    });
    return reply.send({ success: true });
  });
}
