import { FastifyInstance } from 'fastify';
import { z } from 'zod';
import axios from 'axios';
import ytdl from '@distube/ytdl-core';
import ytdlExec from 'yt-dlp-exec';
import fs from 'fs';
import path from 'path';
import { prisma } from '../prisma/client';
import { authenticate } from '../middleware/auth.middleware';
import { config } from '../config';

// Load YouTube agent cookies from project root if it exists
let ytdlAgent: any = undefined;
try {
  const cookiesPath = path.join(process.cwd(), 'youtube_cookies.json');
  if (fs.existsSync(cookiesPath)) {
    const cookies = JSON.parse(fs.readFileSync(cookiesPath, 'utf8'));
    ytdlAgent = ytdl.createAgent(cookies);
    console.log('[MusicRouter] Loaded YouTube cookies agent successfully from youtube_cookies.json.');
  }
} catch (err) {
  console.warn('[MusicRouter] Failed to load youtube_cookies.json for ytdl agent:', err);
}

function convertJsonToNetscape(jsonCookies: any[]): string {
  let output = '# Netscape HTTP Cookie File\n# This file is generated by USCHAT\n\n';
  for (const cookie of jsonCookies) {
    const domain = cookie.domain || '.youtube.com';
    const flag1 = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const pathVal = cookie.path || '/';
    const flag2 = cookie.secure ? 'TRUE' : 'FALSE';
    const expiration = Math.floor(cookie.expirationDate || (Date.now() / 1000 + 3600 * 24 * 365));
    const name = cookie.name;
    const value = cookie.value;
    output += `${domain}\t${flag1}\t${pathVal}\t${flag2}\t${expiration}\t${name}\t${value}\n`;
  }
  return output;
}

const searchSchema = z.object({
  q: z.string().min(1),
});
const playlistCreateSchema = z.object({
  name: z.string().min(1).max(100),
});

const addTrackSchema = z.object({
  title: z.string().min(1),
  artist: z.string().min(1),
  album: z.string().optional().nullable(),
  duration: z.number().int().optional().nullable(),
  coverUrl: z.string().optional().nullable(),
  trackUri: z.string().url(),
});

async function searchYouTube(query: string): Promise<any[]> {
  try {
    const url = `https://www.youtube.com/results?search_query=${encodeURIComponent(query)}`;
    const response = await axios.get(url, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Accept-Language': 'en-US,en;q=0.9',
      },
      timeout: 5000,
    });

    const html = response.data;
    const regex = /var ytInitialData\s*=\s*({.+?});/;
    const match = regex.exec(html);
    if (!match) return [];

    const json = JSON.parse(match[1]);
    const contents = json.contents?.twoColumnSearchResultsRenderer?.primaryContents?.sectionListRenderer?.contents?.[0]?.itemSectionRenderer?.contents || [];

    const tracks: any[] = [];
    for (const item of contents) {
      const video = item.videoRenderer;
      if (!video) continue;

      const title = video.title?.runs?.[0]?.text || '';
      const videoId = video.videoId;
      if (!videoId) continue;

      const artist = video.ownerText?.runs?.[0]?.text || 'Unknown Artist';
      const durationText = video.lengthText?.simpleText || '3:00';
      
      const parts = durationText.split(':').map(Number);
      let duration = 0;
      if (parts.length === 2) {
        duration = parts[0] * 60 + parts[1];
      } else if (parts.length === 3) {
        duration = parts[0] * 3600 + parts[1] * 60 + parts[2];
      }

      const coverUrl = video.thumbnail?.thumbnails?.[0]?.url || null;
      const trackUri = `https://www.youtube.com/watch?v=${videoId}`;

      tracks.push({
        title,
        artist,
        duration,
        trackUri,
        coverUrl,
      });
    }
    return tracks;
  } catch (err) {
    console.error('[YouTubeSearch] Scraper failed:', err);
    return [];
  }
}

export async function musicRoutes(fastify: FastifyInstance) {
  // 1. Search Music via Lavalink Node (with direct YouTube scraper fallback)
  fastify.get('/search', { preHandler: [authenticate] }, async (request, reply) => {
    const { q } = searchSchema.parse(request.query);
    try {
      const lavalinkUrl = `http://${config.lavalink.host}:${config.lavalink.port}/v4/loadtracks`;
      const response = await axios.get(lavalinkUrl, {
        params: { identifier: `ytsearch:${q}` },
        headers: { Authorization: config.lavalink.password },
        timeout: 5000,
      });

      const data = response.data;
      const loadTypeUpper = String(data.loadType).toUpperCase();
      
      if ((loadTypeUpper === 'SEARCH' || loadTypeUpper === 'TRACK_LOADED') && Array.isArray(data.data) && data.data.length > 0) {
        const tracks = data.data.map((item: any) => ({
          title: item.info.title,
          artist: item.info.author,
          duration: Math.floor(item.info.length / 1000),
          trackUri: item.info.uri,
          coverUrl: item.info.artworkUrl || null,
        }));
        return reply.send(tracks);
      }
      
      // Fallback if Lavalink returned empty, search result load type was not matched, or errored
      fastify.log.warn('[MusicRouter] Lavalink search empty/unsupported. Attempting YouTube search fallback...');
      const fallbackTracks = await searchYouTube(q);
      return reply.send(fallbackTracks);
    } catch (err: any) {
      fastify.log.error(err, '[MusicRouter] Lavalink search request failed. Triggering YouTube search fallback...');
      const fallbackTracks = await searchYouTube(q);
      return reply.send(fallbackTracks);
    }
  });

  // 2. Direct Audio Stream Pipe (No HTTP redirect)
  fastify.get('/stream', { preHandler: [authenticate] }, async (request, reply) => {
    const { uri } = z.object({ uri: z.string().url() }).parse(request.query);
    try {
      fastify.log.info({ uri }, '[MusicRouter] Resolving stream with yt-dlp-exec stdout pipe...');

      const jsonCookiesPath = path.join(process.cwd(), 'youtube_cookies.json');
      const netscapeCookiesPath = path.join(process.cwd(), 'youtube_cookies.txt');

      // Convert JSON cookies to Netscape format on-the-fly for yt-dlp
      if (fs.existsSync(jsonCookiesPath)) {
        try {
          const jsonCookies = JSON.parse(fs.readFileSync(jsonCookiesPath, 'utf8'));
          const netscapeStr = convertJsonToNetscape(jsonCookies);
          fs.writeFileSync(netscapeCookiesPath, netscapeStr, 'utf8');
        } catch (err) {
          fastify.log.warn(err, '[MusicRouter] Failed to convert JSON cookies to Netscape format');
        }
      }

      const ytDlpOptions: any = {
        output: '-',
        format: 'bestaudio',
        jsRuntimes: 'node:' + process.execPath,
      };

      if (fs.existsSync(netscapeCookiesPath)) {
        ytDlpOptions.cookies = netscapeCookiesPath;
      }

      // Execute ytdl-exec and stream its stdout directly to Fastify response
      const subprocess = (ytdlExec as any).exec(uri, ytDlpOptions);

      let stderrOutput = '';
      if (subprocess.stderr) {
        subprocess.stderr.on('data', (chunk: any) => {
          stderrOutput += chunk.toString();
        });
      }

      subprocess.on('close', (code: any) => {
        if (code !== 0 && code !== null) {
          fastify.log.error({ code, stderr: stderrOutput.trim() }, '[MusicRouter] yt-dlp subprocess exited with error code');
        }
      });

      // Kill the subprocess if the client disconnects/closes connection
      request.raw.on('close', () => {
        if (!subprocess.killed) {
          fastify.log.info('[MusicRouter] Client disconnected, killing yt-dlp stream process...');
          subprocess.kill();
        }
      });

      subprocess.on('error', (err: any) => {
        fastify.log.error(err, '[MusicRouter] yt-dlp subprocess error');
      });

      reply.header('Content-Type', 'audio/mpeg');
      return reply.send(subprocess.stdout);
    } catch (err: any) {
      fastify.log.error(err, '[MusicRouter] Stream resolution failed');
      return reply.status(500).send({ error: 'Resolution Failed', message: 'Failed to resolve audio stream link' });
    }
  });

  // 3. Playlists CRUD Endpoints
  fastify.get('/playlists', { preHandler: [authenticate] }, async (request, reply) => {
    const playlists = await prisma.playlist.findMany({
      where: { userId: request.user.id },
      include: {
        tracks: { orderBy: { position: 'asc' } },
      },
      orderBy: { createdAt: 'desc' },
    });
    return reply.send(playlists);
  });

  fastify.post('/playlist', { preHandler: [authenticate] }, async (request, reply) => {
    const { name } = playlistCreateSchema.parse(request.body);
    const playlist = await prisma.playlist.create({
      data: {
        userId: request.user.id,
        name,
      },
    });
    return reply.status(201).send(playlist);
  });

  fastify.get('/playlists/:id', { preHandler: [authenticate] }, async (request, reply) => {
    const { id } = request.params as { id: string };
    const playlist = await prisma.playlist.findFirst({
      where: { id, userId: request.user.id },
      include: {
        tracks: { orderBy: { position: 'asc' } },
      },
    });

    if (!playlist) {
      return reply.status(404).send({ error: 'Not Found', message: 'Playlist not found' });
    }
    return reply.send(playlist);
  });

  fastify.delete('/playlist/:id', { preHandler: [authenticate] }, async (request, reply) => {
    const { id } = request.params as { id: string };
    await prisma.playlist.deleteMany({
      where: { id, userId: request.user.id },
    });
    return reply.send({ success: true });
  });

  fastify.post('/playlists/:id/tracks', { preHandler: [authenticate] }, async (request, reply) => {
    const { id } = request.params as { id: string };
    const body = addTrackSchema.parse(request.body);

    const playlist = await prisma.playlist.findFirst({
      where: { id, userId: request.user.id },
    });

    if (!playlist) {
      return reply.status(404).send({ error: 'Not Found', message: 'Playlist not found' });
    }

    const count = await prisma.playlistTrack.count({ where: { playlistId: id } });

    const newTrack = await prisma.playlistTrack.create({
      data: {
        playlistId: id,
        title: body.title,
        artist: body.artist,
        album: body.album,
        duration: body.duration,
        coverUrl: body.coverUrl,
        trackUri: body.trackUri,
        position: count,
      },
    });

    return reply.status(201).send(newTrack);
  });

  fastify.delete('/playlists/:id/tracks/:trackId', { preHandler: [authenticate] }, async (request, reply) => {
    const { id, trackId } = request.params as { id: string; trackId: string };
    
    const playlist = await prisma.playlist.findFirst({
      where: { id, userId: request.user.id },
    });

    if (!playlist) {
      return reply.status(404).send({ error: 'Not Found', message: 'Playlist not found' });
    }

    await prisma.playlistTrack.delete({
      where: { id: trackId },
    });

    return reply.send({ success: true });
  });

  // 4. Liked Songs Endpoints
  fastify.get('/liked', { preHandler: [authenticate] }, async (request, reply) => {
    const liked = await prisma.likedSong.findMany({
      where: { userId: request.user.id },
      orderBy: { createdAt: 'desc' },
    });
    return reply.send(liked);
  });

  fastify.post('/like', { preHandler: [authenticate] }, async (request, reply) => {
    const body = addTrackSchema.parse(request.body);
    const userId = request.user.id;

    // Check if already liked to prevent unique constraint crash
    const existing = await prisma.likedSong.findFirst({
      where: { userId, title: body.title, artist: body.artist },
    });

    if (existing) {
      return reply.status(200).send(existing);
    }

    const liked = await prisma.likedSong.create({
      data: {
        userId,
        title: body.title,
        artist: body.artist,
        album: body.album,
        duration: body.duration,
        coverUrl: body.coverUrl,
        trackUri: body.trackUri,
      },
    });

    return reply.status(201).send(liked);
  });

  fastify.delete('/unlike', { preHandler: [authenticate] }, async (request, reply) => {
    const { trackUri } = z.object({ trackUri: z.string().url() }).parse(request.query);
    await prisma.likedSong.deleteMany({
      where: { trackUri, userId: request.user.id },
    });
    return reply.send({ success: true });
  });
}
