const ytdl = require('yt-dlp-exec');
const fs = require('fs');
const path = require('path');

function convertJsonToNetscape(jsonCookies) {
  let output = '# Netscape HTTP Cookie File\n# This file is generated by USCHAT\n\n';
  for (const cookie of jsonCookies) {
    const domain = cookie.domain || '.youtube.com';
    const flag1 = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const pathVal = cookie.path || '/';
    const flag2 = cookie.secure ? 'TRUE' : 'FALSE';
    const expiration = Math.floor(cookie.expirationDate || (Date.now() / 1000 + 3600 * 24 * 365));
    const name = cookie.name;
    const value = cookie.value;
    output += `${domain}\t${flag1}\t${pathVal}\t${flag2}\t${expiration}\t${name}\t${value}\n`;
  }
  return output;
}

async function main() {
  const jsonPath = path.join(__dirname, '../youtube_cookies.json');
  const netscapePath = path.join(__dirname, '../youtube_cookies.txt');

  if (fs.existsSync(jsonPath)) {
    const cookiesJson = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
    const netscapeStr = convertJsonToNetscape(cookiesJson);
    fs.writeFileSync(netscapePath, netscapeStr, 'utf8');
    console.log('Successfully generated Netscape cookies file!');
  } else {
    console.log('No JSON cookies file found to convert.');
  }

  console.log('Resolving direct stream URL using yt-dlp-exec with Node JS Runtime and Netscape cookies...');
  try {
    const options = {
      getUrl: true,
      format: 'bestaudio',
      jsRuntimes: 'node:' + process.execPath,
    };

    if (fs.existsSync(netscapePath)) {
      options.cookies = netscapePath;
    }

    const url = await ytdl('https://www.youtube.com/watch?v=gJLVTKhTnog', options);
    console.log('SUCCESS! Direct stream URL resolved:', url);
  } catch (err) {
    console.error('YT-DLP-EXEC ERROR:', err.message);
  }
}

main();
